<a href="https://colab.research.google.com/github/Innovatewithapple/keras/blob/main/keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [2]:
filepath='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv'
concrete_data = pd.read_csv(filepath)

concrete_data.head()

   Cement  Blast Furnace Slag  Fly Ash  ...  Fine Aggregate  Age  Strength
0   540.0                 0.0      0.0  ...           676.0   28     79.99
1   540.0                 0.0      0.0  ...           676.0   28     61.89
2   332.5               142.5      0.0  ...           594.0  270     40.27
3   332.5               142.5      0.0  ...           594.0  365     41.05
4   198.6               132.4      0.0  ...           825.5  360     44.30

[5 rows x 9 columns]

In [3]:
concrete_data.shape

(1030, 9)

In [4]:
concrete_data.describe()

            Cement  Blast Furnace Slag  ...          Age     Strength
count  1030.000000         1030.000000  ...  1030.000000  1030.000000
mean    281.167864           73.895825  ...    45.662136    35.817961
std     104.506364           86.279342  ...    63.169912    16.705742
min     102.000000            0.000000  ...     1.000000     2.330000
25%     192.375000            0.000000  ...     7.000000    23.710000
50%     272.900000           22.000000  ...    28.000000    34.445000
75%     350.000000          142.950000  ...    56.000000    46.135000
max     540.000000          359.400000  ...   365.000000    82.600000

[8 rows x 9 columns]

In [5]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [6]:
concrete_data_columns = concrete_data.columns

In [7]:
predictors = concrete_data.drop(columns='Strength')
target = concrete_data['Strength']

In [8]:
predictors

      Cement  Blast Furnace Slag  ...  Fine Aggregate  Age
0      540.0                 0.0  ...           676.0   28
1      540.0                 0.0  ...           676.0   28
2      332.5               142.5  ...           594.0  270
3      332.5               142.5  ...           594.0  365
4      198.6               132.4  ...           825.5  360
...      ...                 ...  ...             ...  ...
1025   276.4               116.0  ...           768.3   28
1026   322.2                 0.0  ...           813.4   28
1027   148.5               139.4  ...           780.0   28
1028   159.1               186.7  ...           788.9   28
1029   260.9               100.5  ...           761.5   28

[1030 rows x 8 columns]

In [12]:
predictors.shape[1]

8

In [15]:
# Split of features
x_train,x_test,y_train,y_test = train_test_split(predictors,target,test_size=0.3,random_state=42)

In [17]:
#start scaling
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [22]:
# Neural Network Starts
model = Sequential()
model.add(Dense(5,activation='relu',input_shape=(x_train.shape[1],)))
model.add(Dense(5,activation='relu'))
model.add(Dense(1)) # here no activation means linear -> regression.

model.compile(optimizer='adam',loss='mean_squared_error')

model.fit(x_train,y_train,epochs=100,validation_split=0.2)

loss = model.evaluate(x_test,y_test)

predict = model.predict(x_test)
mse = mean_squared_error(y_test,predict)
rmse = np.sqrt(mse)
print('Loss: ',loss)
print('MSE: ',mse)
print('RMSE: ',rmse)

# 🧠 FINAL LIST (SAVE THIS)

# You can tune:

# - number of layers
# - neurons
# - learning rate
# - optimizer
# - activation
# - batch size
# - epochs
# - weight initialization
# - regularization
# - dropout

Epoch 1/100

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

18/18 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 1605.5553 - val_loss: 1627.7030
Epoch 2/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1596.6023 - val_loss: 1619.1615
Epoch 3/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1588.4774 - val_loss: 1611.2018
Epoch 4/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1580.8380 - val_loss: 1603.6045
Epoch 5/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 1573.4867 - val_loss: 1596.3417
Epoch 6/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1566.6888 - val_loss: 1589.4335
Epoch 7/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1560.0023 - val_loss: 1582.6958
Epoch 8/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1553.4174 - val_loss: 1575.6923
Epoch 9/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1546.2709 - val_loss: 1567.9347
Epoch 10/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1538.1996 - val_loss: 1558.9355
Epoch 11/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1529.0151 - val_loss: 1548.3331
Epoch 12/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1518.1577 - val_loss: 1536.3282
Epoch 13/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1505.6755 - val_loss: 1522.6962
Epoch 14/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1491.5542 - val_loss: 1507.0552
Epoch 15/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1475.5352 - val_loss: 1489.2439
Epoch 16/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1457.3898 - val_loss: 1469.4376
Epoch 17/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1437.2635 - val_loss: 1447.5872
Epoch 18/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1415.1821 - val_loss: 1423.4672
Epoch 19/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1391.4005 - val_loss: 1396.8889
Epoch 20/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1365.0287 - val_loss: 1368.9517
Epoch 21/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1337.3885 - val_loss: 1338.9021
Epoch 22/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1308.4680 - val_loss: 1306.3563
Epoch 23/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1277.0559 - val_loss: 1273.0231
Epoch 24/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 1245.1127 - val_loss: 1237.9441
Epoch 25/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1211.1539 - val_loss: 1203.1576
Epoch 26/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1178.1705 - val_loss: 1165.6707
Epoch 27/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1143.2941 - val_loss: 1128.4019
Epoch 28/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1108.0900 - val_loss: 1091.3335
Epoch 29/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1073.4838 - val_loss: 1053.7579
Epoch 30/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1038.0566 - val_loss: 1017.5943
Epoch 31/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1004.1461 - val_loss: 980.9116
Epoch 32/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 970.3546 - val_loss: 944.7061
Epoch 33/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 937.4984 - val_loss: 909.1868
Epoch 34/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 905.4651 - val_loss: 874.2874
Epoch 35/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 873.9464 - val_loss: 840.9224
Epoch 36/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 842.6658 - val_loss: 808.4406
Epoch 37/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 811.4941 - val_loss: 775.9207
Epoch 38/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 779.0922 - val_loss: 744.4265
Epoch 39/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 746.0597 - val_loss: 710.9095
Epoch 40/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 712.3015 - val_loss: 675.0229
Epoch 41/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 674.7702 - val_loss: 640.2470
Epoch 42/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 638.9065 - val_loss: 603.3495
Epoch 43/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 601.4664 - val_loss: 567.8201
Epoch 44/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 564.2343 - val_loss: 533.2691
Epoch 45/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 528.6380 - val_loss: 499.6853
Epoch 46/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 493.6061 - val_loss: 469.1633
Epoch 47/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 461.3193 - val_loss: 440.2215
Epoch 48/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 431.1539 - val_loss: 412.7400
Epoch 49/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 404.0666 - val_loss: 386.4169
Epoch 50/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 377.6883 - val_loss: 364.7590
Epoch 51/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 355.4528 - val_loss: 343.9916
Epoch 52/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 335.8499 - val_loss: 324.8981
Epoch 53/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 317.4213 - val_loss: 309.1274
Epoch 54/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 301.7052 - val_loss: 294.2298
Epoch 55/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 287.0379 - val_loss: 280.4104
Epoch 56/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 274.1482 - val_loss: 267.4799
Epoch 57/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 262.3493 - val_loss: 255.8408
Epoch 58/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 252.0034 - val_loss: 245.0915
Epoch 59/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 242.2526 - val_loss: 235.5768
Epoch 60/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 233.4809 - val_loss: 226.7163
Epoch 61/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 225.7700 - val_loss: 218.2663
Epoch 62/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 218.3304 - val_loss: 210.9976
Epoch 63/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 211.4747 - val_loss: 203.6650
Epoch 64/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 205.1581 - val_loss: 196.8767
Epoch 65/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 199.4735 - val_loss: 190.6360
Epoch 66/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 194.0403 - val_loss: 184.9635
Epoch 67/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 189.3079 - val_loss: 180.0998
Epoch 68/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 184.9469 - val_loss: 175.3611
Epoch 69/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 180.6624 - val_loss: 171.3202
Epoch 70/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 176.8731 - val_loss: 167.4610
Epoch 71/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 173.4650 - val_loss: 163.7498
Epoch 72/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 170.1709 - val_loss: 160.4024
Epoch 73/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 167.4707 - val_loss: 157.4982
Epoch 74/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 164.9464 - val_loss: 154.7291
Epoch 75/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 162.5053 - val_loss: 152.1651
Epoch 76/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 160.5109 - val_loss: 150.3745
Epoch 77/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 158.5516 - val_loss: 148.1274
Epoch 78/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 156.6596 - val_loss: 146.5678
Epoch 79/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 154.9805 - val_loss: 144.8166
Epoch 80/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 153.5120 - val_loss: 142.8728
Epoch 81/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 151.9335 - val_loss: 141.4631
Epoch 82/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 150.6442 - val_loss: 139.9705
Epoch 83/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 149.4414 - val_loss: 139.1171
Epoch 84/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 148.2239 - val_loss: 138.0150
Epoch 85/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 147.1800 - val_loss: 137.1073
Epoch 86/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 146.2313 - val_loss: 136.0965
Epoch 87/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 145.3599 - val_loss: 134.9464
Epoch 88/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 144.3289 - val_loss: 134.7252
Epoch 89/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 143.4615 - val_loss: 133.7169
Epoch 90/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 142.7270 - val_loss: 132.6306
Epoch 91/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 141.8149 - val_loss: 132.2574
Epoch 92/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 140.9833 - val_loss: 131.7470
Epoch 93/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 140.1985 - val_loss: 130.9035
Epoch 94/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 139.4694 - val_loss: 130.3776
Epoch 95/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.7198 - val_loss: 130.0706
Epoch 96/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 138.0322 - val_loss: 129.5193
Epoch 97/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137.4375 - val_loss: 128.7547
Epoch 98/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 136.7270 - val_loss: 128.4014
Epoch 99/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 136.2237 - val_loss: 127.7972
Epoch 100/100
18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 135.4724 - val_loss: 127.6958
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 128.4089
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step
Loss:  128.408935546875
MSE:  128.40892384762455
RMSE:  11.33176613982236